### ISSUE TITLE
Chrome extension loads contentscript.js twice

### ISSUE THREAD

**Issue by imre-kerr** [thirdy/forgotten-mods#2]
This results in two `fm_options_elem` elements, one of which is empty. Reading from this then fails.

```
      "matches": ["http://poe.trade/search/*", "http://www.poe.trade/search/*"],
```

My understanding of Chrome extensions is limited, but I have to assume this line in manifest.json is to blame.

**Comment by thirdy** [comment]
Hi. I've not touch this project for a long time. But I don't remember any issues with the chrome extention config. But maybe google broke the compatibility? If so, feel free to make pull request for it.

You can fork this project as I don't have any plans on maintaining it anymore.

I got this functionally implemented in my Durian project:

https://github.com/thirdy/durian/

so.

Cheers!
